// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2ADWzNRkHkKSZmOuAEXE77R2bk8lGjU',
    appId: '1:418262752163:web:3b6473360e40d76d1e9816',
    messagingSenderId: '418262752163',
    projectId: 'courseanalysis-d6b2e',
    authDomain: 'courseanalysis-d6b2e.firebaseapp.com',
    databaseURL:
        'https://courseanalysis-d6b2e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseanalysis-d6b2e.appspot.com',
    measurementId: 'G-ZZDXLY05BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJLCxay_3A32LQkPweyz8dtvdrYwzKtpQ',
    appId: '1:418262752163:android:5f73c42ce31e17e11e9816',
    messagingSenderId: '418262752163',
    projectId: 'courseanalysis-d6b2e',
    databaseURL:
        'https://courseanalysis-d6b2e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseanalysis-d6b2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjEuPbcGH5Sz9nBUMtklaKq1qZQJY2XLE',
    appId: '1:418262752163:ios:3ee351e1c55233ad1e9816',
    messagingSenderId: '418262752163',
    projectId: 'courseanalysis-d6b2e',
    databaseURL:
        'https://courseanalysis-d6b2e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseanalysis-d6b2e.appspot.com',
    iosClientId:
        '418262752163-ul1fo9id5ufpt45j9bmt855am3sf2fhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseanalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjEuPbcGH5Sz9nBUMtklaKq1qZQJY2XLE',
    appId: '1:418262752163:ios:296e1fcdb2dfdd441e9816',
    messagingSenderId: '418262752163',
    projectId: 'courseanalysis-d6b2e',
    databaseURL:
        'https://courseanalysis-d6b2e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseanalysis-d6b2e.appspot.com',
    iosClientId:
        '418262752163-sc0pve9s4ss1v5v0g3qthu9m5k83h3ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseanalysis.RunnerTests',
  );
}
